g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
/bin/sh ../share/genbuild.sh obj/build.h
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/checkpoints.d -o obj/checkpoints.o checkpoints.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/builder.cc -o leveldb/db/builder.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/c.cc -o leveldb/db/c.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/netbase.d -o obj/netbase.o netbase.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/dbformat.cc -o leveldb/db/dbformat.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/db_impl.cc -o leveldb/db/db_impl.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/db_iter.cc -o leveldb/db/db_iter.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/addrman.d -o obj/addrman.o addrman.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/filename.cc -o leveldb/db/filename.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/log_reader.cc -o leveldb/db/log_reader.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/crypter.d -o obj/crypter.o crypter.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/log_writer.cc -o leveldb/db/log_writer.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/memtable.cc -o leveldb/db/memtable.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/repair.cc -o leveldb/db/repair.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/key.d -o obj/key.o key.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/table_cache.cc -o leveldb/db/table_cache.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/version_edit.cc -o leveldb/db/version_edit.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/db.d -o obj/db.o db.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/init.d -o obj/init.o init.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/version_set.cc -o leveldb/db/version_set.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/bitcoind.d -o obj/bitcoind.o bitcoind.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/db/write_batch.cc -o leveldb/db/write_batch.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/block_builder.cc -o leveldb/table/block_builder.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/block.cc -o leveldb/table/block.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/filter_block.cc -o leveldb/table/filter_block.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/format.cc -o leveldb/table/format.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/iterator.cc -o leveldb/table/iterator.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/merger.cc -o leveldb/table/merger.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/table_builder.cc -o leveldb/table/table_builder.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/table.cc -o leveldb/table/table.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/table/two_level_iterator.cc -o leveldb/table/two_level_iterator.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/arena.cc -o leveldb/util/arena.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/bloom.cc -o leveldb/util/bloom.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/keystore.d -o obj/keystore.o keystore.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/cache.cc -o leveldb/util/cache.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/coding.cc -o leveldb/util/coding.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/core.d -o obj/core.o core.cpp
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/comparator.cc -o leveldb/util/comparator.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/crc32c.cc -o leveldb/util/crc32c.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/env.cc -o leveldb/util/env.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/env_posix.cc -o leveldb/util/env_posix.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/env_win.cc -o leveldb/util/env_win.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/filter_policy.cc -o leveldb/util/filter_policy.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/hash.cc -o leveldb/util/hash.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/histogram.cc -o leveldb/util/histogram.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/logging.cc -o leveldb/util/logging.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/options.cc -o leveldb/util/options.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/util/status.cc -o leveldb/util/status.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/port/port_posix.cc -o leveldb/port/port_posix.o
g++ -I. -I./include -fno-builtin-memcmp -pthread -DOS_LINUX -DLEVELDB_PLATFORM_POSIX -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -c leveldb/helpers/memenv/memenv.cc -o leveldb/helpers/memenv/memenv.o
rm -f libleveldb.a
ar -rs libleveldb.a leveldb/db/builder.o leveldb/db/c.o leveldb/db/dbformat.o leveldb/db/db_impl.o leveldb/db/db_iter.o leveldb/db/filename.o leveldb/db/log_reader.o leveldb/db/log_writer.o leveldb/db/memtable.o leveldb/db/repair.o leveldb/db/table_cache.o leveldb/db/version_edit.o leveldb/db/version_set.o leveldb/db/write_batch.o leveldb/table/block_builder.o leveldb/table/block.o leveldb/table/filter_block.o leveldb/table/format.o leveldb/table/iterator.o leveldb/table/merger.o leveldb/table/table_builder.o leveldb/table/table.o leveldb/table/two_level_iterator.o leveldb/util/arena.o leveldb/util/bloom.o leveldb/util/cache.o leveldb/util/coding.o leveldb/util/comparator.o leveldb/util/crc32c.o leveldb/util/env.o leveldb/util/env_posix.o leveldb/util/env_win.o leveldb/util/filter_policy.o leveldb/util/hash.o leveldb/util/histogram.o leveldb/util/logging.o leveldb/util/options.o leveldb/util/status.o leveldb/port/port_posix.o
rm -f libmemenv.a
ar -rs libmemenv.a leveldb/helpers/memenv/memenv.o
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/main.d -o obj/main.o main.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/net.d -o obj/net.o net.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/protocol.d -o obj/protocol.o protocol.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/bitcoinrpc.d -o obj/bitcoinrpc.o bitcoinrpc.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/rpcdump.d -o obj/rpcdump.o rpcdump.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/rpcnet.d -o obj/rpcnet.o rpcnet.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/rpcmining.d -o obj/rpcmining.o rpcmining.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/rpcwallet.d -o obj/rpcwallet.o rpcwallet.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/rpcblockchain.d -o obj/rpcblockchain.o rpcblockchain.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/rpcrawtransaction.d -o obj/rpcrawtransaction.o rpcrawtransaction.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/script.d -o obj/script.o script.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/sync.d -o obj/sync.o sync.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/util.d -o obj/util.o util.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/wallet.d -o obj/wallet.o wallet.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/walletdb.d -o obj/walletdb.o walletdb.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/hash.d -o obj/hash.o hash.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/bloom.d -o obj/bloom.o bloom.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/noui.d -o obj/noui.o noui.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/leveldb.d -o obj/leveldb.o leveldb.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/txdb.d -o obj/txdb.o txdb.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/chainparams.d -o obj/chainparams.o chainparams.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/scrypt.d -o obj/scrypt.o scrypt.cpp
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/version.d -o obj/version.o version.cpp
g++ -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -D_FILE_OFFSET_BITS=64 -I/work/new/parallelcoin/src -I/work/new/parallelcoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -I/work/new/parallelcoin/src/leveldb/include -I/work/new/parallelcoin/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o parallelcoind leveldb/libleveldb.a obj/alert.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/db.o obj/init.o obj/bitcoind.o obj/keystore.o obj/core.o obj/main.o obj/net.o obj/protocol.o obj/bitcoinrpc.o obj/rpcdump.o obj/rpcnet.o obj/rpcmining.o obj/rpcwallet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/script.o obj/sync.o obj/util.o obj/wallet.o obj/walletdb.o obj/hash.o obj/bloom.o obj/noui.o obj/leveldb.o obj/txdb.o obj/chainparams.o obj/scrypt.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread /work/new/parallelcoin/src/leveldb/libleveldb.a /work/new/parallelcoin/src/leveldb/libmemenv.a
